// for Visual Studio Code extention "REST Client"
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client
//

@hostname = localhost
@port =  8000
@host = {{hostname}}:{{port}}
@x-db_for_base-token = 45ec5067-2529-4e02-b87b-37f8a4281fa8

### Get kitting list - Success
# GET  http://{{host}}/api/accounts HTTP/1.1
# content-type: application/json
# Authorization: alloww

# {}

GET  http://{{host}}/func/get-payment-method-list HTTP/1.1