"""Delete unused table

Revision ID: 44d252461ab9
Revises: 1bcdf2f7e69c
Create Date: 2023-05-24 15:11:32.359816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44d252461ab9'
down_revision = '1bcdf2f7e69c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_account_role')
    op.drop_table('m_account_group')
    op.drop_table('m_role_operation')
    op.drop_table('m_role')
    op.drop_table('m_operation')
    op.drop_table('m_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_role',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='ロールID'),
    sa.Column('role_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='ロール名'),
    sa.Column('version', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='バージョン:楽観的排他で利用'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='削除日時'),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='削除者'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
    sa.ForeignKeyConstraint(['created_by'], ['m_accounts.account_id'], name='m_role_ibfk_1'),
    sa.ForeignKeyConstraint(['deleted_by'], ['m_accounts.account_id'], name='m_role_ibfk_2'),
    sa.ForeignKeyConstraint(['modified_by'], ['m_accounts.account_id'], name='m_role_ibfk_3'),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('m_role_operation',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='ロールID'),
    sa.Column('operation_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='オペレーションID'),
    sa.Column('version', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='バージョン:楽観的排他で利用'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='削除日時'),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='削除者'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
    sa.ForeignKeyConstraint(['created_by'], ['m_accounts.account_id'], name='m_role_operation_ibfk_1'),
    sa.ForeignKeyConstraint(['deleted_by'], ['m_accounts.account_id'], name='m_role_operation_ibfk_2'),
    sa.ForeignKeyConstraint(['modified_by'], ['m_accounts.account_id'], name='m_role_operation_ibfk_3'),
    sa.ForeignKeyConstraint(['operation_id'], ['m_operation.operation_id'], name='m_role_operation_ibfk_4'),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('m_account_group',
    sa.Column('account_group_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='アカウントID'),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='グループID'),
    sa.Column('is_manager', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='管理者フラグ'),
    sa.Column('version', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='バージョン:楽観的排他で利用'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='削除日時'),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='削除者'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
    sa.ForeignKeyConstraint(['account_id'], ['m_accounts.account_id'], name='m_account_group_ibfk_1'),
    sa.ForeignKeyConstraint(['created_by'], ['m_accounts.account_id'], name='m_account_group_ibfk_2'),
    sa.ForeignKeyConstraint(['deleted_by'], ['m_accounts.account_id'], name='m_account_group_ibfk_3'),
    sa.ForeignKeyConstraint(['group_id'], ['m_group.group_id'], name='m_account_group_ibfk_4'),
    sa.ForeignKeyConstraint(['modified_by'], ['m_accounts.account_id'], name='m_account_group_ibfk_5'),
    sa.PrimaryKeyConstraint('account_group_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('m_group',
    sa.Column('group_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='グループID:1以上であること'),
    sa.Column('group_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='グループ名称'),
    sa.Column('group_cd', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='グループコード'),
    sa.Column('parent_group_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='親グループID:0 は親グループが無し'),
    sa.Column('version', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='バージョン:楽観的排他で利用'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='削除日時'),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='削除者'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
    sa.ForeignKeyConstraint(['created_by'], ['m_accounts.account_id'], name='m_group_ibfk_1'),
    sa.ForeignKeyConstraint(['deleted_by'], ['m_accounts.account_id'], name='m_group_ibfk_2'),
    sa.ForeignKeyConstraint(['modified_by'], ['m_accounts.account_id'], name='m_group_ibfk_3'),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('m_account_role',
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='アカウントID'),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='ロールID'),
    sa.Column('version', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='バージョン:楽観的排他で利用'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='削除日時'),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='削除者'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
    sa.ForeignKeyConstraint(['account_id'], ['m_accounts.account_id'], name='m_account_role_ibfk_1'),
    sa.ForeignKeyConstraint(['created_by'], ['m_accounts.account_id'], name='m_account_role_ibfk_2'),
    sa.ForeignKeyConstraint(['deleted_by'], ['m_accounts.account_id'], name='m_account_role_ibfk_3'),
    sa.ForeignKeyConstraint(['modified_by'], ['m_accounts.account_id'], name='m_account_role_ibfk_4'),
    sa.ForeignKeyConstraint(['role_id'], ['m_role.role_id'], name='m_account_role_ibfk_5'),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('m_operation',
    sa.Column('operation_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='オペレーションID'),
    sa.Column('operation_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='オペレーション名'),
    sa.Column('version', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='バージョン:楽観的排他で利用'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='削除日時'),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='削除者'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
    sa.ForeignKeyConstraint(['created_by'], ['m_accounts.account_id'], name='m_operation_ibfk_1'),
    sa.ForeignKeyConstraint(['deleted_by'], ['m_accounts.account_id'], name='m_operation_ibfk_2'),
    sa.ForeignKeyConstraint(['modified_by'], ['m_accounts.account_id'], name='m_operation_ibfk_3'),
    sa.PrimaryKeyConstraint('operation_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
