"""update database

Revision ID: 4648fcd67583
Revises: 
Create Date: 2023-06-14 09:11:07.960450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4648fcd67583'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_vehicle_img',
    sa.Column('vehicleImageid', sa.Integer(), nullable=False),
    sa.Column('vehicleId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vehicleId'], ['m_vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('vehicleImageid')
    )
    op.alter_column('m_account_base', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.add_column('m_vehicles', sa.Column('vehicle_seat', sa.Integer(), nullable=True, comment='Số lượng ghế'))
    op.add_column('m_vehicles', sa.Column('vehicle_type', sa.String(length=200), nullable=True, comment='Kiểu xe'))
    op.add_column('m_vehicles', sa.Column('vehicle_value', sa.Float(), nullable=True, comment='Giá xe'))
    op.add_column('m_vehicles', sa.Column('vehicleEngine', sa.String(length=200), nullable=True, comment='Động cơ xe'))
    op.drop_constraint('m_vehicles_ibfk_2', 'm_vehicles', type_='foreignkey')
    op.drop_column('m_vehicles', 'model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_vehicles', sa.Column('model_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='メーカーID'))
    op.create_foreign_key('m_vehicles_ibfk_2', 'm_vehicles', 'm_models', ['model_id'], ['model_id'])
    op.drop_column('m_vehicles', 'vehicleEngine')
    op.drop_column('m_vehicles', 'vehicle_value')
    op.drop_column('m_vehicles', 'vehicle_type')
    op.drop_column('m_vehicles', 'vehicle_seat')
    op.alter_column('m_account_base', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_table('m_vehicle_img')
    # ### end Alembic commands ###
