"""add rentalOrderCart1

Revision ID: 4fbca64466bc
Revises: 
Create Date: 2023-06-15 17:04:03.692786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbca64466bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_rental_order_cart', sa.Column('rental_start_date', sa.DateTime(), nullable=True, comment='レンタル開始日'))
    op.add_column('t_rental_order_cart', sa.Column('rental_end_date', sa.DateTime(), nullable=True, comment='レンタル終了日'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_rental_order_cart', 'rental_end_date')
    op.drop_column('t_rental_order_cart', 'rental_start_date')
    # ### end Alembic commands ###
