"""Update vehicles/Rental table

Revision ID: 70418dc6cf54
Revises: d12a3250a04c
Create Date: 2023-06-07 10:34:26.962227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70418dc6cf54'
down_revision = 'd12a3250a04c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_models',
    sa.Column('model_id', sa.Integer(), nullable=False, comment='モデルID'),
    sa.Column('model_name', sa.String(length=200), nullable=True, comment='名前モデル'),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.alter_column('m_payment_methods', 'payment_method_id',
               existing_type=mysql.INTEGER(),
               comment='お支払い方法ID',
               existing_comment='保険ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('m_payment_methods', 'payment_method_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='名前お支払い方法',
               existing_comment='名前保険',
               existing_nullable=True)
    op.add_column('m_vehicles', sa.Column('model_id', sa.Integer(), nullable=True, comment='メーカーID'))
    op.add_column('m_vehicles', sa.Column('year', sa.Integer(), nullable=True, comment='製造年'))
    op.add_column('m_vehicles', sa.Column('mileage', sa.Integer(), nullable=True, comment='車の走行距離(km)'))
    op.add_column('m_vehicles', sa.Column('vehicle_status', sa.Integer(), nullable=True, comment='車の状態：1-利用可能、2-レンタル済、3-保守中'))
    op.create_foreign_key(None, 'm_vehicles', 'm_models', ['model_id'], ['model_id'])
    op.add_column('t_rental_order_detail', sa.Column('rental_start_date', sa.DateTime(), nullable=False, comment='レンタル開始日'))
    op.add_column('t_rental_order_detail', sa.Column('rental_end_date', sa.DateTime(), nullable=False, comment='レンタル終了日'))
    op.alter_column('t_rental_order_detail', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='作成者',
               existing_comment='作成処理:プログラムで設定、API名、関数名',
               existing_nullable=True)
    op.alter_column('t_rental_order_detail', 'modified_by',
               existing_type=mysql.INTEGER(),
               comment='更新者',
               existing_comment='更新処理:プログラムで設定、API名、関数名',
               existing_nullable=True)
    op.drop_column('t_rental_order_detail', 'retal_start_date')
    op.drop_column('t_rental_order_detail', 'retal_end_date')
    op.add_column('t_rental_orders', sa.Column('paymented_at', sa.DateTime(), nullable=False, comment='支払日'))
    op.alter_column('t_rental_orders', 'payment_method_id',
               existing_type=mysql.INTEGER(),
               comment='お支払い方法ID',
               existing_comment='作成処理:プログラムで設定、API名、関数名',
               existing_nullable=True)
    op.alter_column('t_rental_orders', 'rental_status',
               existing_type=mysql.INTEGER(),
               comment='注文の状態。1:新規、2:確認中、3:確認済、4:支払い済み、5:キャンセル',
               existing_comment='作成処理:プログラムで設定、API名、関数名',
               existing_nullable=True)
    op.alter_column('t_rental_orders', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='作成者',
               existing_comment='作成処理:プログラムで設定、API名、関数名',
               existing_nullable=True)
    op.alter_column('t_rental_orders', 'modified_by',
               existing_type=mysql.INTEGER(),
               comment='更新者',
               existing_comment='更新処理:プログラムで設定、API名、関数名',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_rental_orders', 'modified_by',
               existing_type=mysql.INTEGER(),
               comment='更新処理:プログラムで設定、API名、関数名',
               existing_comment='更新者',
               existing_nullable=True)
    op.alter_column('t_rental_orders', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='作成処理:プログラムで設定、API名、関数名',
               existing_comment='作成者',
               existing_nullable=True)
    op.alter_column('t_rental_orders', 'rental_status',
               existing_type=mysql.INTEGER(),
               comment='作成処理:プログラムで設定、API名、関数名',
               existing_comment='注文の状態。1:新規、2:確認中、3:確認済、4:支払い済み、5:キャンセル',
               existing_nullable=True)
    op.alter_column('t_rental_orders', 'payment_method_id',
               existing_type=mysql.INTEGER(),
               comment='作成処理:プログラムで設定、API名、関数名',
               existing_comment='お支払い方法ID',
               existing_nullable=True)
    op.drop_column('t_rental_orders', 'paymented_at')
    op.add_column('t_rental_order_detail', sa.Column('retal_end_date', mysql.DATETIME(), nullable=False, comment='レンタル終了日'))
    op.add_column('t_rental_order_detail', sa.Column('retal_start_date', mysql.DATETIME(), nullable=False, comment='レンタル開始日'))
    op.alter_column('t_rental_order_detail', 'modified_by',
               existing_type=mysql.INTEGER(),
               comment='更新処理:プログラムで設定、API名、関数名',
               existing_comment='更新者',
               existing_nullable=True)
    op.alter_column('t_rental_order_detail', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='作成処理:プログラムで設定、API名、関数名',
               existing_comment='作成者',
               existing_nullable=True)
    op.drop_column('t_rental_order_detail', 'rental_end_date')
    op.drop_column('t_rental_order_detail', 'rental_start_date')
    op.drop_constraint(None, 'm_vehicles', type_='foreignkey')
    op.drop_column('m_vehicles', 'vehicle_status')
    op.drop_column('m_vehicles', 'mileage')
    op.drop_column('m_vehicles', 'year')
    op.drop_column('m_vehicles', 'model_id')
    op.alter_column('m_payment_methods', 'payment_method_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='名前保険',
               existing_comment='名前お支払い方法',
               existing_nullable=True)
    op.alter_column('m_payment_methods', 'payment_method_id',
               existing_type=mysql.INTEGER(),
               comment='保険ID',
               existing_comment='お支払い方法ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('m_models')
    # ### end Alembic commands ###
