"""update rentalOrderCart

Revision ID: 9141af6e5a87
Revises: 
Create Date: 2023-06-20 22:37:07.218524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9141af6e5a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_car_cart',
    sa.Column('car_cart_id', sa.Integer(), nullable=False, comment='発注明細ID:自動採番'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='アカウントID'),
    sa.Column('vehicle_id', sa.Integer(), nullable=False, comment='車両ID'),
    sa.Column('option_id', sa.String(length=200), nullable=True, comment='車両ID'),
    sa.Column('insurance_id', sa.String(length=200), nullable=True, comment='保険ID'),
    sa.Column('rental_start_date', sa.DateTime(), nullable=False, comment='レンタル開始日'),
    sa.Column('rental_end_date', sa.DateTime(), nullable=False, comment='レンタル終了日'),
    sa.Column('total_hour', sa.Float(), nullable=False, comment='Tổng giờ'),
    sa.Column('total_hour_car', sa.Float(), nullable=False, comment='Chi phí xe theo giờ'),
    sa.Column('total_option', sa.Float(), nullable=True, comment='Tổng chi phí option'),
    sa.Column('total_insurance', sa.Float(), nullable=True, comment='Tổng chi phí bảo hiểm'),
    sa.Column('total_cost', sa.Float(), nullable=False, comment='Tổng chi phí'),
    sa.Column('status_cart', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='0: giỏ hàng; 1: đã đặt'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='作成日時:プログラムでは設定しない'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='作成者'),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新日時:プログラムでは設定しない'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='更新者'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='削除日時'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='削除者'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('False'), nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
    sa.ForeignKeyConstraint(['account_id'], ['m_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['m_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['m_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['m_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['m_vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('car_cart_id')
    )
    op.alter_column('m_vehicles', 'vehicle_model',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='Kiểu xe')
    op.alter_column('m_vehicles', 'vehicle_value',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='Giá xe')
    op.add_column('t_rental_order_detail', sa.Column('insurance_id', sa.String(length=200), nullable=False, comment='ID bao hiem'))
    op.drop_constraint('t_rental_order_detail_ibfk_4', 't_rental_order_detail', type_='foreignkey')
    op.alter_column('t_rental_orders', 'paymented_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='支払日')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_rental_orders', 'paymented_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='支払日')
    op.create_foreign_key('t_rental_order_detail_ibfk_4', 't_rental_order_detail', 'm_options', ['option_id'], ['option_id'])
    op.drop_column('t_rental_order_detail', 'insurance_id')
    op.alter_column('m_vehicles', 'vehicle_value',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='Giá xe')
    op.alter_column('m_vehicles', 'vehicle_model',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='Kiểu xe')
    op.drop_table('t_car_cart')
    # ### end Alembic commands ###
