"""Edit miragation

Revision ID: f0fc567b1a08
Revises: 
Create Date: 2023-06-13 13:59:51.921105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0fc567b1a08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_vehicles', sa.Column('vehicleEngine', sa.String(length=200), nullable=True, comment='Động cơ xe'))
    op.drop_column('m_vehicles', 'vehicleImage_id')
    op.drop_column('m_vehicles', 'vehicle_Engine')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_vehicles', sa.Column('vehicle_Engine', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='Động cơ xe'))
    op.add_column('m_vehicles', sa.Column('vehicleImage_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='メーカーID'))
    op.drop_column('m_vehicles', 'vehicleEngine')
    # ### end Alembic commands ###
